[theme]
primaryColor = "#0EA5E9"
backgroundColor = "#040608"
secondaryBackgroundColor = "#06090E"
textColor = "#C9D1D9"
base = "dark"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"
